services:
  # ==========================================================
  # Next.js application
  # ==========================================================
  taskcraft:
    image: 172.18.18.66:4040/mithun/taskcraft:v1
    container_name: taskcraft
    restart: unless-stopped

    env_file:
      - .env

    environment:
      NODE_ENV: production

      APP_URL: ${APP_URL}

      DATABASE_URL: postgresql://${POSTGRES_USER:-taskcraft}:${POSTGRES_PASSWORD:-taskcraft}@taskcraft_pg:5432/${POSTGRES_DB:-task_craft_db}

    ports:
      - "4141:3000"

    networks:
      - finx-network

    depends_on:
      - taskcraft_telegram_bot

  # ==========================================================
  # Telegram bot
  # ==========================================================
  taskcraft_telegram_bot:
    image: 172.18.18.66:4040/mithun/taskcraft:v1
    container_name: taskcraft_telegram_bot
    restart: unless-stopped

    env_file:
      - .env

    environment:
      NODE_ENV: production

      APP_URL: ${APP_URL}

      DATABASE_URL: postgresql://${POSTGRES_USER:-taskcraft}:${POSTGRES_PASSWORD:-taskcraft}@taskcraft_pg:5432/${POSTGRES_DB:-task_craft_db}

    command:
      - node
      - scripts/telegram-bot.js

    networks:
      - finx-network

networks:
  finx-network:
    external: true
